quantiles: [0.1, 0.5, 0.9]


TreeModel:
  boosting_type: 'gbdt'
  features: ['Load_DA', 'Solar_DA', 'WindOn_DA','WindOff_DA','Temp_Act', 'Coal_fM','Gas_fM', 'month', 'is_weekend', 'hour','is_holiday']
  lags: [24, 48, 168]
  target_col: "Price"
  pred_length: 24 # predict day-ahead jointly
  train_length: 2000
  kwargs:
    min_data_in_leaf: 20
    num_leaves: 31
    max_depth: -1
    learning_rate: 0.01
    n_estimators: 100
    random_state: 42
    lambda_l2: 1.0



LinearModel:
  boosting_type: 'gbdt'
  lags: [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
  features: []  
  target_col: "Price"
  pred_length: 24 # predict day-ahead jointly
  train_length: 2000
  kwargs:
    random_state: 42
    alpha: 20